/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package forma.thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class IntArray implements org.apache.thrift.TBase<IntArray, IntArray._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IntArray");

  private static final org.apache.thrift.protocol.TField INTS_FIELD_DESC = new org.apache.thrift.protocol.TField("ints", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IntArrayStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IntArrayTupleSchemeFactory());
  }

  public List<Integer> ints; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INTS((short)1, "ints");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTS
          return INTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTS, new org.apache.thrift.meta_data.FieldMetaData("ints", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IntArray.class, metaDataMap);
  }

  public IntArray() {
  }

  public IntArray(
    List<Integer> ints)
  {
    this();
    this.ints = ints;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IntArray(IntArray other) {
    if (other.isSetInts()) {
      List<Integer> __this__ints = new ArrayList<Integer>();
      for (Integer other_element : other.ints) {
        __this__ints.add(other_element);
      }
      this.ints = __this__ints;
    }
  }

  public IntArray deepCopy() {
    return new IntArray(this);
  }

  @Override
  public void clear() {
    this.ints = null;
  }

  public int getIntsSize() {
    return (this.ints == null) ? 0 : this.ints.size();
  }

  public java.util.Iterator<Integer> getIntsIterator() {
    return (this.ints == null) ? null : this.ints.iterator();
  }

  public void addToInts(int elem) {
    if (this.ints == null) {
      this.ints = new ArrayList<Integer>();
    }
    this.ints.add(elem);
  }

  public List<Integer> getInts() {
    return this.ints;
  }

  public IntArray setInts(List<Integer> ints) {
    this.ints = ints;
    return this;
  }

  public void unsetInts() {
    this.ints = null;
  }

  /** Returns true if field ints is set (has been assigned a value) and false otherwise */
  public boolean isSetInts() {
    return this.ints != null;
  }

  public void setIntsIsSet(boolean value) {
    if (!value) {
      this.ints = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INTS:
      if (value == null) {
        unsetInts();
      } else {
        setInts((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INTS:
      return getInts();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INTS:
      return isSetInts();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IntArray)
      return this.equals((IntArray)that);
    return false;
  }

  public boolean equals(IntArray that) {
    if (that == null)
      return false;

    boolean this_present_ints = true && this.isSetInts();
    boolean that_present_ints = true && that.isSetInts();
    if (this_present_ints || that_present_ints) {
      if (!(this_present_ints && that_present_ints))
        return false;
      if (!this.ints.equals(that.ints))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_ints = true && (isSetInts());
    builder.append(present_ints);
    if (present_ints)
      builder.append(ints);

    return builder.toHashCode();
  }

  public int compareTo(IntArray other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    IntArray typedOther = (IntArray)other;

    lastComparison = Boolean.valueOf(isSetInts()).compareTo(typedOther.isSetInts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ints, typedOther.ints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IntArray(");
    boolean first = true;

    sb.append("ints:");
    if (this.ints == null) {
      sb.append("null");
    } else {
      sb.append(this.ints);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IntArrayStandardSchemeFactory implements SchemeFactory {
    public IntArrayStandardScheme getScheme() {
      return new IntArrayStandardScheme();
    }
  }

  private static class IntArrayStandardScheme extends StandardScheme<IntArray> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IntArray struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.ints = new ArrayList<Integer>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  int _elem10; // required
                  _elem10 = iprot.readI32();
                  struct.ints.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setIntsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IntArray struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ints != null) {
        oprot.writeFieldBegin(INTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.ints.size()));
          for (int _iter11 : struct.ints)
          {
            oprot.writeI32(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IntArrayTupleSchemeFactory implements SchemeFactory {
    public IntArrayTupleScheme getScheme() {
      return new IntArrayTupleScheme();
    }
  }

  private static class IntArrayTupleScheme extends TupleScheme<IntArray> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IntArray struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetInts()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetInts()) {
        {
          oprot.writeI32(struct.ints.size());
          for (int _iter12 : struct.ints)
          {
            oprot.writeI32(_iter12);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IntArray struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.ints = new ArrayList<Integer>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            int _elem15; // required
            _elem15 = iprot.readI32();
            struct.ints.add(_elem15);
          }
        }
        struct.setIntsIsSet(true);
      }
    }
  }

}

