/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package forma.schema;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class FormaNeighborValue implements TBase<FormaNeighborValue, FormaNeighborValue._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("FormaNeighborValue");

  private static final TField FIRE_VALUE_FIELD_DESC = new TField("fireValue", TType.STRUCT, (short)1);
  private static final TField NUM_NEIGHBORS_FIELD_DESC = new TField("numNeighbors", TType.I32, (short)2);
  private static final TField AVG_SHORT_DROP_FIELD_DESC = new TField("avgShortDrop", TType.DOUBLE, (short)3);
  private static final TField MIN_SHORT_DROP_FIELD_DESC = new TField("minShortDrop", TType.DOUBLE, (short)4);
  private static final TField AVG_LONG_DROP_FIELD_DESC = new TField("avgLongDrop", TType.DOUBLE, (short)5);
  private static final TField MIN_LONG_DROP_FIELD_DESC = new TField("minLongDrop", TType.DOUBLE, (short)6);
  private static final TField AVG_TSTAT_FIELD_DESC = new TField("avgTStat", TType.DOUBLE, (short)7);
  private static final TField MIN_TSTAT_FIELD_DESC = new TField("minTStat", TType.DOUBLE, (short)8);

  public FireTuple fireValue;
  public int numNeighbors;
  public double avgShortDrop;
  public double minShortDrop;
  public double avgLongDrop;
  public double minLongDrop;
  public double avgTStat;
  public double minTStat;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    FIRE_VALUE((short)1, "fireValue"),
    NUM_NEIGHBORS((short)2, "numNeighbors"),
    AVG_SHORT_DROP((short)3, "avgShortDrop"),
    MIN_SHORT_DROP((short)4, "minShortDrop"),
    AVG_LONG_DROP((short)5, "avgLongDrop"),
    MIN_LONG_DROP((short)6, "minLongDrop"),
    AVG_TSTAT((short)7, "avgTStat"),
    MIN_TSTAT((short)8, "minTStat");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FIRE_VALUE
          return FIRE_VALUE;
        case 2: // NUM_NEIGHBORS
          return NUM_NEIGHBORS;
        case 3: // AVG_SHORT_DROP
          return AVG_SHORT_DROP;
        case 4: // MIN_SHORT_DROP
          return MIN_SHORT_DROP;
        case 5: // AVG_LONG_DROP
          return AVG_LONG_DROP;
        case 6: // MIN_LONG_DROP
          return MIN_LONG_DROP;
        case 7: // AVG_TSTAT
          return AVG_TSTAT;
        case 8: // MIN_TSTAT
          return MIN_TSTAT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMNEIGHBORS_ISSET_ID = 0;
  private static final int __AVGSHORTDROP_ISSET_ID = 1;
  private static final int __MINSHORTDROP_ISSET_ID = 2;
  private static final int __AVGLONGDROP_ISSET_ID = 3;
  private static final int __MINLONGDROP_ISSET_ID = 4;
  private static final int __AVGTSTAT_ISSET_ID = 5;
  private static final int __MINTSTAT_ISSET_ID = 6;
  private BitSet __isset_bit_vector = new BitSet(7);

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FIRE_VALUE, new FieldMetaData("fireValue", TFieldRequirementType.DEFAULT, 
        new StructMetaData(TType.STRUCT, FireTuple.class)));
    tmpMap.put(_Fields.NUM_NEIGHBORS, new FieldMetaData("numNeighbors", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    tmpMap.put(_Fields.AVG_SHORT_DROP, new FieldMetaData("avgShortDrop", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.MIN_SHORT_DROP, new FieldMetaData("minShortDrop", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.AVG_LONG_DROP, new FieldMetaData("avgLongDrop", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.MIN_LONG_DROP, new FieldMetaData("minLongDrop", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.AVG_TSTAT, new FieldMetaData("avgTStat", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.MIN_TSTAT, new FieldMetaData("minTStat", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(FormaNeighborValue.class, metaDataMap);
  }

  public FormaNeighborValue() {
  }

  public FormaNeighborValue(
    FireTuple fireValue,
    int numNeighbors,
    double avgShortDrop,
    double minShortDrop,
    double avgLongDrop,
    double minLongDrop,
    double avgTStat,
    double minTStat)
  {
    this();
    this.fireValue = fireValue;
    this.numNeighbors = numNeighbors;
    setNumNeighborsIsSet(true);
    this.avgShortDrop = avgShortDrop;
    setAvgShortDropIsSet(true);
    this.minShortDrop = minShortDrop;
    setMinShortDropIsSet(true);
    this.avgLongDrop = avgLongDrop;
    setAvgLongDropIsSet(true);
    this.minLongDrop = minLongDrop;
    setMinLongDropIsSet(true);
    this.avgTStat = avgTStat;
    setAvgTStatIsSet(true);
    this.minTStat = minTStat;
    setMinTStatIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FormaNeighborValue(FormaNeighborValue other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetFireValue()) {
      this.fireValue = new FireTuple(other.fireValue);
    }
    this.numNeighbors = other.numNeighbors;
    this.avgShortDrop = other.avgShortDrop;
    this.minShortDrop = other.minShortDrop;
    this.avgLongDrop = other.avgLongDrop;
    this.minLongDrop = other.minLongDrop;
    this.avgTStat = other.avgTStat;
    this.minTStat = other.minTStat;
  }

  public FormaNeighborValue deepCopy() {
    return new FormaNeighborValue(this);
  }

  @Override
  public void clear() {
    this.fireValue = null;
    setNumNeighborsIsSet(false);
    this.numNeighbors = 0;
    setAvgShortDropIsSet(false);
    this.avgShortDrop = 0.0;
    setMinShortDropIsSet(false);
    this.minShortDrop = 0.0;
    setAvgLongDropIsSet(false);
    this.avgLongDrop = 0.0;
    setMinLongDropIsSet(false);
    this.minLongDrop = 0.0;
    setAvgTStatIsSet(false);
    this.avgTStat = 0.0;
    setMinTStatIsSet(false);
    this.minTStat = 0.0;
  }

  public FireTuple getFireValue() {
    return this.fireValue;
  }

  public FormaNeighborValue setFireValue(FireTuple fireValue) {
    this.fireValue = fireValue;
    return this;
  }

  public void unsetFireValue() {
    this.fireValue = null;
  }

  /** Returns true if field fireValue is set (has been asigned a value) and false otherwise */
  public boolean isSetFireValue() {
    return this.fireValue != null;
  }

  public void setFireValueIsSet(boolean value) {
    if (!value) {
      this.fireValue = null;
    }
  }

  public int getNumNeighbors() {
    return this.numNeighbors;
  }

  public FormaNeighborValue setNumNeighbors(int numNeighbors) {
    this.numNeighbors = numNeighbors;
    setNumNeighborsIsSet(true);
    return this;
  }

  public void unsetNumNeighbors() {
    __isset_bit_vector.clear(__NUMNEIGHBORS_ISSET_ID);
  }

  /** Returns true if field numNeighbors is set (has been asigned a value) and false otherwise */
  public boolean isSetNumNeighbors() {
    return __isset_bit_vector.get(__NUMNEIGHBORS_ISSET_ID);
  }

  public void setNumNeighborsIsSet(boolean value) {
    __isset_bit_vector.set(__NUMNEIGHBORS_ISSET_ID, value);
  }

  public double getAvgShortDrop() {
    return this.avgShortDrop;
  }

  public FormaNeighborValue setAvgShortDrop(double avgShortDrop) {
    this.avgShortDrop = avgShortDrop;
    setAvgShortDropIsSet(true);
    return this;
  }

  public void unsetAvgShortDrop() {
    __isset_bit_vector.clear(__AVGSHORTDROP_ISSET_ID);
  }

  /** Returns true if field avgShortDrop is set (has been asigned a value) and false otherwise */
  public boolean isSetAvgShortDrop() {
    return __isset_bit_vector.get(__AVGSHORTDROP_ISSET_ID);
  }

  public void setAvgShortDropIsSet(boolean value) {
    __isset_bit_vector.set(__AVGSHORTDROP_ISSET_ID, value);
  }

  public double getMinShortDrop() {
    return this.minShortDrop;
  }

  public FormaNeighborValue setMinShortDrop(double minShortDrop) {
    this.minShortDrop = minShortDrop;
    setMinShortDropIsSet(true);
    return this;
  }

  public void unsetMinShortDrop() {
    __isset_bit_vector.clear(__MINSHORTDROP_ISSET_ID);
  }

  /** Returns true if field minShortDrop is set (has been asigned a value) and false otherwise */
  public boolean isSetMinShortDrop() {
    return __isset_bit_vector.get(__MINSHORTDROP_ISSET_ID);
  }

  public void setMinShortDropIsSet(boolean value) {
    __isset_bit_vector.set(__MINSHORTDROP_ISSET_ID, value);
  }

  public double getAvgLongDrop() {
    return this.avgLongDrop;
  }

  public FormaNeighborValue setAvgLongDrop(double avgLongDrop) {
    this.avgLongDrop = avgLongDrop;
    setAvgLongDropIsSet(true);
    return this;
  }

  public void unsetAvgLongDrop() {
    __isset_bit_vector.clear(__AVGLONGDROP_ISSET_ID);
  }

  /** Returns true if field avgLongDrop is set (has been asigned a value) and false otherwise */
  public boolean isSetAvgLongDrop() {
    return __isset_bit_vector.get(__AVGLONGDROP_ISSET_ID);
  }

  public void setAvgLongDropIsSet(boolean value) {
    __isset_bit_vector.set(__AVGLONGDROP_ISSET_ID, value);
  }

  public double getMinLongDrop() {
    return this.minLongDrop;
  }

  public FormaNeighborValue setMinLongDrop(double minLongDrop) {
    this.minLongDrop = minLongDrop;
    setMinLongDropIsSet(true);
    return this;
  }

  public void unsetMinLongDrop() {
    __isset_bit_vector.clear(__MINLONGDROP_ISSET_ID);
  }

  /** Returns true if field minLongDrop is set (has been asigned a value) and false otherwise */
  public boolean isSetMinLongDrop() {
    return __isset_bit_vector.get(__MINLONGDROP_ISSET_ID);
  }

  public void setMinLongDropIsSet(boolean value) {
    __isset_bit_vector.set(__MINLONGDROP_ISSET_ID, value);
  }

  public double getAvgTStat() {
    return this.avgTStat;
  }

  public FormaNeighborValue setAvgTStat(double avgTStat) {
    this.avgTStat = avgTStat;
    setAvgTStatIsSet(true);
    return this;
  }

  public void unsetAvgTStat() {
    __isset_bit_vector.clear(__AVGTSTAT_ISSET_ID);
  }

  /** Returns true if field avgTStat is set (has been asigned a value) and false otherwise */
  public boolean isSetAvgTStat() {
    return __isset_bit_vector.get(__AVGTSTAT_ISSET_ID);
  }

  public void setAvgTStatIsSet(boolean value) {
    __isset_bit_vector.set(__AVGTSTAT_ISSET_ID, value);
  }

  public double getMinTStat() {
    return this.minTStat;
  }

  public FormaNeighborValue setMinTStat(double minTStat) {
    this.minTStat = minTStat;
    setMinTStatIsSet(true);
    return this;
  }

  public void unsetMinTStat() {
    __isset_bit_vector.clear(__MINTSTAT_ISSET_ID);
  }

  /** Returns true if field minTStat is set (has been asigned a value) and false otherwise */
  public boolean isSetMinTStat() {
    return __isset_bit_vector.get(__MINTSTAT_ISSET_ID);
  }

  public void setMinTStatIsSet(boolean value) {
    __isset_bit_vector.set(__MINTSTAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FIRE_VALUE:
      if (value == null) {
        unsetFireValue();
      } else {
        setFireValue((FireTuple)value);
      }
      break;

    case NUM_NEIGHBORS:
      if (value == null) {
        unsetNumNeighbors();
      } else {
        setNumNeighbors((Integer)value);
      }
      break;

    case AVG_SHORT_DROP:
      if (value == null) {
        unsetAvgShortDrop();
      } else {
        setAvgShortDrop((Double)value);
      }
      break;

    case MIN_SHORT_DROP:
      if (value == null) {
        unsetMinShortDrop();
      } else {
        setMinShortDrop((Double)value);
      }
      break;

    case AVG_LONG_DROP:
      if (value == null) {
        unsetAvgLongDrop();
      } else {
        setAvgLongDrop((Double)value);
      }
      break;

    case MIN_LONG_DROP:
      if (value == null) {
        unsetMinLongDrop();
      } else {
        setMinLongDrop((Double)value);
      }
      break;

    case AVG_TSTAT:
      if (value == null) {
        unsetAvgTStat();
      } else {
        setAvgTStat((Double)value);
      }
      break;

    case MIN_TSTAT:
      if (value == null) {
        unsetMinTStat();
      } else {
        setMinTStat((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FIRE_VALUE:
      return getFireValue();

    case NUM_NEIGHBORS:
      return new Integer(getNumNeighbors());

    case AVG_SHORT_DROP:
      return new Double(getAvgShortDrop());

    case MIN_SHORT_DROP:
      return new Double(getMinShortDrop());

    case AVG_LONG_DROP:
      return new Double(getAvgLongDrop());

    case MIN_LONG_DROP:
      return new Double(getMinLongDrop());

    case AVG_TSTAT:
      return new Double(getAvgTStat());

    case MIN_TSTAT:
      return new Double(getMinTStat());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FIRE_VALUE:
      return isSetFireValue();
    case NUM_NEIGHBORS:
      return isSetNumNeighbors();
    case AVG_SHORT_DROP:
      return isSetAvgShortDrop();
    case MIN_SHORT_DROP:
      return isSetMinShortDrop();
    case AVG_LONG_DROP:
      return isSetAvgLongDrop();
    case MIN_LONG_DROP:
      return isSetMinLongDrop();
    case AVG_TSTAT:
      return isSetAvgTStat();
    case MIN_TSTAT:
      return isSetMinTStat();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FormaNeighborValue)
      return this.equals((FormaNeighborValue)that);
    return false;
  }

  public boolean equals(FormaNeighborValue that) {
    if (that == null)
      return false;

    boolean this_present_fireValue = true && this.isSetFireValue();
    boolean that_present_fireValue = true && that.isSetFireValue();
    if (this_present_fireValue || that_present_fireValue) {
      if (!(this_present_fireValue && that_present_fireValue))
        return false;
      if (!this.fireValue.equals(that.fireValue))
        return false;
    }

    boolean this_present_numNeighbors = true;
    boolean that_present_numNeighbors = true;
    if (this_present_numNeighbors || that_present_numNeighbors) {
      if (!(this_present_numNeighbors && that_present_numNeighbors))
        return false;
      if (this.numNeighbors != that.numNeighbors)
        return false;
    }

    boolean this_present_avgShortDrop = true;
    boolean that_present_avgShortDrop = true;
    if (this_present_avgShortDrop || that_present_avgShortDrop) {
      if (!(this_present_avgShortDrop && that_present_avgShortDrop))
        return false;
      if (this.avgShortDrop != that.avgShortDrop)
        return false;
    }

    boolean this_present_minShortDrop = true;
    boolean that_present_minShortDrop = true;
    if (this_present_minShortDrop || that_present_minShortDrop) {
      if (!(this_present_minShortDrop && that_present_minShortDrop))
        return false;
      if (this.minShortDrop != that.minShortDrop)
        return false;
    }

    boolean this_present_avgLongDrop = true;
    boolean that_present_avgLongDrop = true;
    if (this_present_avgLongDrop || that_present_avgLongDrop) {
      if (!(this_present_avgLongDrop && that_present_avgLongDrop))
        return false;
      if (this.avgLongDrop != that.avgLongDrop)
        return false;
    }

    boolean this_present_minLongDrop = true;
    boolean that_present_minLongDrop = true;
    if (this_present_minLongDrop || that_present_minLongDrop) {
      if (!(this_present_minLongDrop && that_present_minLongDrop))
        return false;
      if (this.minLongDrop != that.minLongDrop)
        return false;
    }

    boolean this_present_avgTStat = true;
    boolean that_present_avgTStat = true;
    if (this_present_avgTStat || that_present_avgTStat) {
      if (!(this_present_avgTStat && that_present_avgTStat))
        return false;
      if (this.avgTStat != that.avgTStat)
        return false;
    }

    boolean this_present_minTStat = true;
    boolean that_present_minTStat = true;
    if (this_present_minTStat || that_present_minTStat) {
      if (!(this_present_minTStat && that_present_minTStat))
        return false;
      if (this.minTStat != that.minTStat)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FormaNeighborValue other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FormaNeighborValue typedOther = (FormaNeighborValue)other;

    lastComparison = Boolean.valueOf(isSetFireValue()).compareTo(typedOther.isSetFireValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFireValue()) {
      lastComparison = TBaseHelper.compareTo(this.fireValue, typedOther.fireValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNumNeighbors()).compareTo(typedOther.isSetNumNeighbors());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumNeighbors()) {
      lastComparison = TBaseHelper.compareTo(this.numNeighbors, typedOther.numNeighbors);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAvgShortDrop()).compareTo(typedOther.isSetAvgShortDrop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAvgShortDrop()) {
      lastComparison = TBaseHelper.compareTo(this.avgShortDrop, typedOther.avgShortDrop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinShortDrop()).compareTo(typedOther.isSetMinShortDrop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinShortDrop()) {
      lastComparison = TBaseHelper.compareTo(this.minShortDrop, typedOther.minShortDrop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAvgLongDrop()).compareTo(typedOther.isSetAvgLongDrop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAvgLongDrop()) {
      lastComparison = TBaseHelper.compareTo(this.avgLongDrop, typedOther.avgLongDrop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinLongDrop()).compareTo(typedOther.isSetMinLongDrop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinLongDrop()) {
      lastComparison = TBaseHelper.compareTo(this.minLongDrop, typedOther.minLongDrop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAvgTStat()).compareTo(typedOther.isSetAvgTStat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAvgTStat()) {
      lastComparison = TBaseHelper.compareTo(this.avgTStat, typedOther.avgTStat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinTStat()).compareTo(typedOther.isSetMinTStat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinTStat()) {
      lastComparison = TBaseHelper.compareTo(this.minTStat, typedOther.minTStat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // FIRE_VALUE
          if (field.type == TType.STRUCT) {
            this.fireValue = new FireTuple();
            this.fireValue.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // NUM_NEIGHBORS
          if (field.type == TType.I32) {
            this.numNeighbors = iprot.readI32();
            setNumNeighborsIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // AVG_SHORT_DROP
          if (field.type == TType.DOUBLE) {
            this.avgShortDrop = iprot.readDouble();
            setAvgShortDropIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // MIN_SHORT_DROP
          if (field.type == TType.DOUBLE) {
            this.minShortDrop = iprot.readDouble();
            setMinShortDropIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // AVG_LONG_DROP
          if (field.type == TType.DOUBLE) {
            this.avgLongDrop = iprot.readDouble();
            setAvgLongDropIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // MIN_LONG_DROP
          if (field.type == TType.DOUBLE) {
            this.minLongDrop = iprot.readDouble();
            setMinLongDropIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // AVG_TSTAT
          if (field.type == TType.DOUBLE) {
            this.avgTStat = iprot.readDouble();
            setAvgTStatIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // MIN_TSTAT
          if (field.type == TType.DOUBLE) {
            this.minTStat = iprot.readDouble();
            setMinTStatIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.fireValue != null) {
      oprot.writeFieldBegin(FIRE_VALUE_FIELD_DESC);
      this.fireValue.write(oprot);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(NUM_NEIGHBORS_FIELD_DESC);
    oprot.writeI32(this.numNeighbors);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(AVG_SHORT_DROP_FIELD_DESC);
    oprot.writeDouble(this.avgShortDrop);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(MIN_SHORT_DROP_FIELD_DESC);
    oprot.writeDouble(this.minShortDrop);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(AVG_LONG_DROP_FIELD_DESC);
    oprot.writeDouble(this.avgLongDrop);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(MIN_LONG_DROP_FIELD_DESC);
    oprot.writeDouble(this.minLongDrop);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(AVG_TSTAT_FIELD_DESC);
    oprot.writeDouble(this.avgTStat);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(MIN_TSTAT_FIELD_DESC);
    oprot.writeDouble(this.minTStat);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FormaNeighborValue(");
    boolean first = true;

    sb.append("fireValue:");
    if (this.fireValue == null) {
      sb.append("null");
    } else {
      sb.append(this.fireValue);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("numNeighbors:");
    sb.append(this.numNeighbors);
    first = false;
    if (!first) sb.append(", ");
    sb.append("avgShortDrop:");
    sb.append(this.avgShortDrop);
    first = false;
    if (!first) sb.append(", ");
    sb.append("minShortDrop:");
    sb.append(this.minShortDrop);
    first = false;
    if (!first) sb.append(", ");
    sb.append("avgLongDrop:");
    sb.append(this.avgLongDrop);
    first = false;
    if (!first) sb.append(", ");
    sb.append("minLongDrop:");
    sb.append(this.minLongDrop);
    first = false;
    if (!first) sb.append(", ");
    sb.append("avgTStat:");
    sb.append(this.avgTStat);
    first = false;
    if (!first) sb.append(", ");
    sb.append("minTStat:");
    sb.append(this.minTStat);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

