/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package forma.schema;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class IntArray implements TBase<IntArray, IntArray._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("IntArray");

  private static final TField INTS_FIELD_DESC = new TField("ints", TType.LIST, (short)1);

  public List<Integer> ints;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    INTS((short)1, "ints");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTS
          return INTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTS, new FieldMetaData("ints", TFieldRequirementType.DEFAULT, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(IntArray.class, metaDataMap);
  }

  public IntArray() {
  }

  public IntArray(
    List<Integer> ints)
  {
    this();
    this.ints = ints;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IntArray(IntArray other) {
    if (other.isSetInts()) {
      List<Integer> __this__ints = new ArrayList<Integer>();
      for (Integer other_element : other.ints) {
        __this__ints.add(other_element);
      }
      this.ints = __this__ints;
    }
  }

  public IntArray deepCopy() {
    return new IntArray(this);
  }

  @Override
  public void clear() {
    this.ints = null;
  }

  public int getIntsSize() {
    return (this.ints == null) ? 0 : this.ints.size();
  }

  public java.util.Iterator<Integer> getIntsIterator() {
    return (this.ints == null) ? null : this.ints.iterator();
  }

  public void addToInts(int elem) {
    if (this.ints == null) {
      this.ints = new ArrayList<Integer>();
    }
    this.ints.add(elem);
  }

  public List<Integer> getInts() {
    return this.ints;
  }

  public IntArray setInts(List<Integer> ints) {
    this.ints = ints;
    return this;
  }

  public void unsetInts() {
    this.ints = null;
  }

  /** Returns true if field ints is set (has been asigned a value) and false otherwise */
  public boolean isSetInts() {
    return this.ints != null;
  }

  public void setIntsIsSet(boolean value) {
    if (!value) {
      this.ints = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INTS:
      if (value == null) {
        unsetInts();
      } else {
        setInts((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INTS:
      return getInts();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INTS:
      return isSetInts();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IntArray)
      return this.equals((IntArray)that);
    return false;
  }

  public boolean equals(IntArray that) {
    if (that == null)
      return false;

    boolean this_present_ints = true && this.isSetInts();
    boolean that_present_ints = true && that.isSetInts();
    if (this_present_ints || that_present_ints) {
      if (!(this_present_ints && that_present_ints))
        return false;
      if (!this.ints.equals(that.ints))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(IntArray other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    IntArray typedOther = (IntArray)other;

    lastComparison = Boolean.valueOf(isSetInts()).compareTo(typedOther.isSetInts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInts()) {
      lastComparison = TBaseHelper.compareTo(this.ints, typedOther.ints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // INTS
          if (field.type == TType.LIST) {
            {
              TList _list4 = iprot.readListBegin();
              this.ints = new ArrayList<Integer>(_list4.size);
              for (int _i5 = 0; _i5 < _list4.size; ++_i5)
              {
                int _elem6;
                _elem6 = iprot.readI32();
                this.ints.add(_elem6);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.ints != null) {
      oprot.writeFieldBegin(INTS_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.I32, this.ints.size()));
        for (int _iter7 : this.ints)
        {
          oprot.writeI32(_iter7);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IntArray(");
    boolean first = true;

    sb.append("ints:");
    if (this.ints == null) {
      sb.append("null");
    } else {
      sb.append(this.ints);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

