/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package forma.schema;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ShortArray implements org.apache.thrift.TBase<ShortArray, ShortArray._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ShortArray");

  private static final org.apache.thrift.protocol.TField SHORTS_FIELD_DESC = new org.apache.thrift.protocol.TField("shorts", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ShortArrayStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ShortArrayTupleSchemeFactory());
  }

  public List<Short> shorts; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SHORTS((short)1, "shorts");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SHORTS
          return SHORTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SHORTS, new org.apache.thrift.meta_data.FieldMetaData("shorts", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ShortArray.class, metaDataMap);
  }

  public ShortArray() {
  }

  public ShortArray(
    List<Short> shorts)
  {
    this();
    this.shorts = shorts;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ShortArray(ShortArray other) {
    if (other.isSetShorts()) {
      List<Short> __this__shorts = new ArrayList<Short>();
      for (Short other_element : other.shorts) {
        __this__shorts.add(other_element);
      }
      this.shorts = __this__shorts;
    }
  }

  public ShortArray deepCopy() {
    return new ShortArray(this);
  }

  @Override
  public void clear() {
    this.shorts = null;
  }

  public int getShortsSize() {
    return (this.shorts == null) ? 0 : this.shorts.size();
  }

  public java.util.Iterator<Short> getShortsIterator() {
    return (this.shorts == null) ? null : this.shorts.iterator();
  }

  public void addToShorts(short elem) {
    if (this.shorts == null) {
      this.shorts = new ArrayList<Short>();
    }
    this.shorts.add(elem);
  }

  public List<Short> getShorts() {
    return this.shorts;
  }

  public ShortArray setShorts(List<Short> shorts) {
    this.shorts = shorts;
    return this;
  }

  public void unsetShorts() {
    this.shorts = null;
  }

  /** Returns true if field shorts is set (has been assigned a value) and false otherwise */
  public boolean isSetShorts() {
    return this.shorts != null;
  }

  public void setShortsIsSet(boolean value) {
    if (!value) {
      this.shorts = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SHORTS:
      if (value == null) {
        unsetShorts();
      } else {
        setShorts((List<Short>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SHORTS:
      return getShorts();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SHORTS:
      return isSetShorts();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ShortArray)
      return this.equals((ShortArray)that);
    return false;
  }

  public boolean equals(ShortArray that) {
    if (that == null)
      return false;

    boolean this_present_shorts = true && this.isSetShorts();
    boolean that_present_shorts = true && that.isSetShorts();
    if (this_present_shorts || that_present_shorts) {
      if (!(this_present_shorts && that_present_shorts))
        return false;
      if (!this.shorts.equals(that.shorts))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_shorts = true && (isSetShorts());
    builder.append(present_shorts);
    if (present_shorts)
      builder.append(shorts);

    return builder.toHashCode();
  }

  public int compareTo(ShortArray other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ShortArray typedOther = (ShortArray)other;

    lastComparison = Boolean.valueOf(isSetShorts()).compareTo(typedOther.isSetShorts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShorts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.shorts, typedOther.shorts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ShortArray(");
    boolean first = true;

    sb.append("shorts:");
    if (this.shorts == null) {
      sb.append("null");
    } else {
      sb.append(this.shorts);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ShortArrayStandardSchemeFactory implements SchemeFactory {
    public ShortArrayStandardScheme getScheme() {
      return new ShortArrayStandardScheme();
    }
  }

  private static class ShortArrayStandardScheme extends StandardScheme<ShortArray> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ShortArray struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SHORTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.shorts = new ArrayList<Short>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  short _elem2; // required
                  _elem2 = iprot.readI16();
                  struct.shorts.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setShortsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ShortArray struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.shorts != null) {
        oprot.writeFieldBegin(SHORTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I16, struct.shorts.size()));
          for (short _iter3 : struct.shorts)
          {
            oprot.writeI16(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ShortArrayTupleSchemeFactory implements SchemeFactory {
    public ShortArrayTupleScheme getScheme() {
      return new ShortArrayTupleScheme();
    }
  }

  private static class ShortArrayTupleScheme extends TupleScheme<ShortArray> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ShortArray struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetShorts()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetShorts()) {
        {
          oprot.writeI32(struct.shorts.size());
          for (short _iter4 : struct.shorts)
          {
            oprot.writeI16(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ShortArray struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I16, iprot.readI32());
          struct.shorts = new ArrayList<Short>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            short _elem7; // required
            _elem7 = iprot.readI16();
            struct.shorts.add(_elem7);
          }
        }
        struct.setShortsIsSet(true);
      }
    }
  }

}

